### ISSUE TITLE
Invalid Handle 0:4

### ISSUE THREAD

**Issue by UWPA** [Bara/CSGOItems#2]
When running my server I get this error:
This happens with timeout set to 0 and 120 etc.
L 04/01/2020 - 18:57:30: [SM] Exception reported: invalid handle 0 (error: 4)
L 04/01/2020 - 18:57:30: [SM] Blaming: ItemLog.smx
L 04/01/2020 - 18:57:30: [SM] Call stack trace:
L 04/01/2020 - 18:57:30: [SM]   [0] File.WriteLine
L 04/01/2020 - 18:57:30: [SM]   [1] Line 105, d:\Cloud\SourcePawn\GitHub\CSGOItems\addons\sourcemod\scripting\ItemLog.sp::CSGOItems_OnItemsSynced
L 04/01/2020 - 18:57:30: [SM]   [3] Call_Finish
L 04/01/2020 - 18:57:30: [SM]   [4] Line 1195, d:\Cloud\SourcePawn\GitHub\CSGOItems\addons\sourcemod\scripting\CSGO_Items.sp::SyncItemData
L 04/01/2020 - 18:57:30: [SM]   [5] Line 871, d:\Cloud\SourcePawn\GitHub\CSGOItems\addons\sourcemod\scripting\CSGO_Items.sp::Timer_SyncSchema

**Comment by Bara** [comment]
`ItemLog` can't be created in the `logs`-Folder. Probably a permission issue on your side or just create this folder.

And ItemLog is just for testing changes.
